a=int(input("enter the first value:"))
b=int(input("enter the second value:"))
print("the addition is:",a+b)
print("the difference is:",a-b)
print("the multiplication is:",a*b)
print("the division is :",a/b)
print("the modulu is :",a%b)
print("the floor division is:",a//b)
